<?php

use App\Country;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    protected $countries = [
        ['countryname' => "Afghanistan", 'countrycode' => "https://restcountries.eu/data/afg.svg"],
        ['countryname' => "Albania", 'countrycode' => "https://restcountries.eu/data/alb.svg"],
        ['countryname' => "Algeria", 'countrycode' => "https://restcountries.eu/data/dza.svg"],
        ['countryname' => "Andorra", 'countrycode' => "https://restcountries.eu/data/and.svg"],
        ['countryname' => "Angola", 'countrycode' => "https://restcountries.eu/data/ago.svg"],
        ['countryname' => "Anguilla", 'countrycode' => "https://restcountries.eu/data/aia.svg"],
        ['countryname' => "Antarctica", 'countrycode' => "https://restcountries.eu/data/ata.svg"],
        ['countryname' => "Antigua and Barbuda", 'countrycode' => "https://restcountries.eu/data/atg.svg"],
        ['countryname' => "Argentina", 'countrycode' => "https://restcountries.eu/data/arg.svg"],
        ['countryname' => "Armenia", 'countrycode' => "https://restcountries.eu/data/arm.svg"],
        ['countryname' => "Aruba", 'countrycode' => "https://restcountries.eu/data/abw.svg"],
        ['countryname' => "Australia", 'countrycode' => "https://restcountries.eu/data/aus.svg"],
        ['countryname' => "Austria", 'countrycode' => "https://restcountries.eu/data/aut.svg"],
        ['countryname' => "Azerbaijan", 'countrycode' => "https://restcountries.eu/data/aze.svg"],
        ['countryname' => "Bahamas", 'countrycode' => "https://restcountries.eu/data/bhs.svg"],
        ['countryname' => "Bahrain", 'countrycode' => "https://restcountries.eu/data/bhr.svg"],
        ['countryname' => "Bangladesh", 'countrycode' => "https://restcountries.eu/data/bgd.svg"],
        ['countryname' => "Barbados", 'countrycode' => "https://restcountries.eu/data/brb.svg"],
        ['countryname' => "Belarus", 'countrycode' => "https://restcountries.eu/data/blr.svg"],
        ['countryname' => "Belgium", 'countrycode' => "https://restcountries.eu/data/bel.svg"],
        ['countryname' => "Belize", 'countrycode' => "https://restcountries.eu/data/blz.svg"],
        ['countryname' => "Benin", 'countrycode' => "https://restcountries.eu/data/ben.svg"],
        ['countryname' => "Bermuda", 'countrycode' => "https://restcountries.eu/data/bmu.svg"],
        ['countryname' => "Bhutan", 'countrycode' => "https://restcountries.eu/data/btn.svg"],
        ['countryname' => "Bolivia", 'countrycode' => "https://restcountries.eu/data/bol.svg"],
        ['countryname' => "Bosnia and Herzegovina", 'countrycode' => "https://restcountries.eu/data/bih.svg"],
        ['countryname' => "Botswana", 'countrycode' => "https://restcountries.eu/data/bwa.svg"],
        ['countryname' => "Brazil", 'countrycode' => "https://restcountries.eu/data/bra.svg"],
        ['countryname' => "Brunei", 'countrycode' => "https://restcountries.eu/data/brn.svg"],
        ['countryname' => "Bulgaria", 'countrycode' => "https://restcountries.eu/data/bgr.svg"],
        ['countryname' => "Burkina Faso", 'countrycode' => "https://restcountries.eu/data/bfa.svg"],
        ['countryname' => "Burundi", 'countrycode' => "https://restcountries.eu/data/bdi.svg"],
        ['countryname' => "Cambodia", 'countrycode' => "https://restcountries.eu/data/khm.svg"],
        ['countryname' => "Cameroon", 'countrycode' => "https://restcountries.eu/data/cmr.svg"],
        ['countryname' => "Canada", 'countrycode' => "https://restcountries.eu/data/can.svg"],
        ['countryname' => "Cabo Verde", 'countrycode' => "https://restcountries.eu/data/cpv.svg"],
        ['countryname' => "Central African Republic", 'countrycode' => "https://restcountries.eu/data/caf.svg"],
        ['countryname' => "Chad", 'countrycode' => "https://restcountries.eu/data/tcd.svg"],
        ['countryname' => "Chile", 'countrycode' => "https://restcountries.eu/data/chl.svg"],
        ['countryname' => "China", 'countrycode' => "https://restcountries.eu/data/chn.svg"],
        ['countryname' => "Colombia", 'countrycode' => "https://restcountries.eu/data/col.svg"],
        ['countryname' => "Comoros", 'countrycode' => "https://restcountries.eu/data/com.svg"],
        ['countryname' => "Congo", 'countrycode' => "https://restcountries.eu/data/cog.svg"],
        ['countryname' => "Democratic Republic of the Congo", 'countrycode' => "https://restcountries.eu/data/cod.svg"],
        ['countryname' => "Costa Rica", 'countrycode' => "https://restcountries.eu/data/cri.svg"],
        ['countryname' => "Croatia", 'countrycode' => "https://restcountries.eu/data/hrv.svg"],
        ['countryname' => "Cuba", 'countrycode' => "https://restcountries.eu/data/cub.svg"],
        ['countryname' => "Cyprus", 'countrycode' => "https://restcountries.eu/data/cyp.svg"],
        ['countryname' => "Czech Republic", 'countrycode' => "https://restcountries.eu/data/cze.svg"],
        ['countryname' => "Denmark", 'countrycode' => "https://restcountries.eu/data/dnk.svg"],
        ['countryname' => "Djibouti", 'countrycode' => "https://restcountries.eu/data/dji.svg"],
        ['countryname' => "Dominica", 'countrycode' => "https://restcountries.eu/data/dma.svg"],
        ['countryname' => "Dominican Republic", 'countrycode' => "https://restcountries.eu/data/dom.svg"],
        ['countryname' => "Ecuador", 'countrycode' => "https://restcountries.eu/data/ecu.svg"],
        ['countryname' => "Egypt", 'countrycode' => "https://restcountries.eu/data/egy.svg"],
        ['countryname' => "El Salvador", 'countrycode' => "https://restcountries.eu/data/slv.svg"],
        ['countryname' => "Equatorial Guinea", 'countrycode' => "https://restcountries.eu/data/gnq.svg"],
        ['countryname' => "Eritrea", 'countrycode' => "https://restcountries.eu/data/eri.svg"],
        ['countryname' => "Estonia", 'countrycode' => "https://restcountries.eu/data/est.svg"],
        ['countryname' => "Ethiopia", 'countrycode' => "https://restcountries.eu/data/eth.svg"],
        ['countryname' => "Fiji", 'countrycode' => "https://restcountries.eu/data/fji.svg"],
        ['countryname' => "Finland", 'countrycode' => "https://restcountries.eu/data/fin.svg"],
        ['countryname' => "France", 'countrycode' => "https://restcountries.eu/data/fra.svg"],
        ['countryname' => "Gabon", 'countrycode' => "https://restcountries.eu/data/gab.svg"],
        ['countryname' => "Gambia", 'countrycode' => "https://restcountries.eu/data/gmb.svg"],
        ['countryname' => "Georgia", 'countrycode' => "https://restcountries.eu/data/geo.svg"],
        ['countryname' => "Germany", 'countrycode' => "https://restcountries.eu/data/deu.svg"],
        ['countryname' => "Ghana", 'countrycode' => "https://restcountries.eu/data/gha.svg"],
        ['countryname' => "Gibraltar", 'countrycode' => "https://restcountries.eu/data/gib.svg"],
        ['countryname' => "Greece", 'countrycode' => "https://restcountries.eu/data/grc.svg"],
        ['countryname' => "Grenada", 'countrycode' => "https://restcountries.eu/data/grd.svg"],
        ['countryname' => "Guadeloupe", 'countrycode' => "https://restcountries.eu/data/glp.svg"],
        ['countryname' => "Guam", 'countrycode' => "https://restcountries.eu/data/gum.svg"],
        ['countryname' => "Guatemala", 'countrycode' => "https://restcountries.eu/data/gtm.svg"],
        ['countryname' => "Guinea", 'countrycode' => "https://restcountries.eu/data/gin.svg"],
        ['countryname' => "Guinea-Bissau", 'countrycode' => "https://restcountries.eu/data/gnb.svg"],
        ['countryname' => "Guyana", 'countrycode' => "https://restcountries.eu/data/guy.svg"],
        ['countryname' => "Haiti", 'countrycode' => "https://restcountries.eu/data/hti.svg"],
        ['countryname' => "Honduras", 'countrycode' => "https://restcountries.eu/data/hnd.svg"],
        ['countryname' => "Hungary", 'countrycode' => "https://restcountries.eu/data/hun.svg"],
        ['countryname' => "Iceland", 'countrycode' => "https://restcountries.eu/data/isl.svg"],
        ['countryname' => "India", 'countrycode' => "https://restcountries.eu/data/ind.svg"],
        ['countryname' => "Indonesia", 'countrycode' => "https://restcountries.eu/data/idn.svg"],
        ['countryname' => "Cote dIvoire", 'countrycode' => "https://restcountries.eu/data/civ.svg"],
        ['countryname' => 'Iran', 'countrycode' => "https://restcountries.eu/data/irn.svg"],
        ['countryname' => 'Iraq', 'countrycode' => "https://restcountries.eu/data/irq.svg"],
        ['countryname' => 'Ireland', 'countrycode' => "https://restcountries.eu/data/irl.svg"],
        ['countryname' => 'Israel', 'countrycode' => "https://restcountries.eu/data/isr.svg"],
        ['countryname' => 'Italy', 'countrycode' => "https://restcountries.eu/data/ita.svg"],
        ['countryname' => 'Jamaica', 'countrycode' => "https://restcountries.eu/data/jam.svg"],
        ['countryname' => 'Japan', 'countrycode' => "https://restcountries.eu/data/jpn.svg"],
        ['countryname' => 'Jersey', 'countrycode' => "https://restcountries.eu/data/jey.svg"],
        ['countryname' => 'Jordan', 'countrycode' => "https://restcountries.eu/data/jor.svg"],
        ['countryname' => 'Kazakhstan', 'countrycode' => "https://restcountries.eu/data/kaz.svg"],
        ['countryname' => 'Kenya', 'countrycode' => "https://restcountries.eu/data/ken.svg"],
        ['countryname' => 'Kiribati', 'countrycode' => "https://restcountries.eu/data/kir.svg"],
        ['countryname' => 'Kuwait', 'countrycode' => "https://restcountries.eu/data/kwt.svg"],
        ['countryname' => 'Kyrgyzstan', 'countrycode' => "https://restcountries.eu/data/kgz.svg"],
        ['countryname' => 'Lao', 'countrycode' => "https://restcountries.eu/data/lao.svg"],
        ['countryname' => 'Latvia', 'countrycode' => "https://restcountries.eu/data/lva.svg"],
        ['countryname' => 'Lebanon', 'countrycode' => "https://restcountries.eu/data/lbn.svg"],
        ['countryname' => 'Lesotho', 'countrycode' => "https://restcountries.eu/data/lso.svg"],
        ['countryname' => 'Liberia', 'countrycode' => "https://restcountries.eu/data/lbr.svg"],
        ['countryname' => 'Libya', 'countrycode' => "https://restcountries.eu/data/lby.svg"],
        ['countryname' => 'Liechtenstein', 'countrycode' => "https://restcountries.eu/data/lie.svg"],
        ['countryname' => 'Lithuania', 'countrycode' => "https://restcountries.eu/data/ltu.svg"],
        ['countryname' => 'Luxembourg', 'countrycode' => "https://restcountries.eu/data/lux.svg"],
        ['countryname' => 'Macedonia', 'countrycode' => "https://restcountries.eu/data/mkd.svg"],
        ['countryname' => 'Madagascar', 'countrycode' => "https://restcountries.eu/data/mdg.svg"],
        ['countryname' => 'Malawi', 'countrycode' => "https://restcountries.eu/data/mwi.svg"],
        ['countryname' => 'Malaysia', 'countrycode' => "https://restcountries.eu/data/mys . svg"],
        ['countryname' => 'Maldives', 'countrycode' => "https://restcountries.eu/data/mdv.svg"],
        ['countryname' => 'Mali', 'countrycode' => "https://restcountries.eu/data/mli.svg"],
        ['countryname' => 'Malta', 'countrycode' => "https://restcountries.eu/data/mlt.svg"],
        ['countryname' => 'Marshall Islands', 'countrycode' => "https://restcountries.eu/data/mhl.svg"],
        ['countryname' => 'Martinique', 'countrycode' => "https://restcountries.eu/data/mtq.svg"],
        ['countryname' => 'Mauritania', 'countrycode' => "https://restcountries.eu/data/mrt . svg"],
        ['countryname' => 'Mauritius', 'countrycode' => "https://restcountries.eu/data/mus.svg"],
        ['countryname' => 'Mexico', 'countrycode' => "https://restcountries.eu/data/mex.svg"],
        ['countryname' => 'Micronesia', 'countrycode' => "https://restcountries.eu/data/fsm.svg"],
        ['countryname' => "Moldova", 'countrycode' => "https://restcountries.eu/data/mda.svg"],
        ['countryname' => "Monaco", 'countrycode' => "https://restcountries.eu/data/mco.svg"],
        ['countryname' => "Mongolia", 'countrycode' => "https://restcountries.eu/data/mng.svg"],
        ['countryname' => "Montenegro", 'countrycode' => "https://restcountries.eu/data/mne.svg"],
        ['countryname' => "Morocco", 'countrycode' => "https://restcountries.eu/data/mar.svg"],
        ['countryname' => "Mozambique", 'countrycode' => "https://restcountries.eu/data/moz.svg"],
        ['countryname' => "Myanmar", 'countrycode' => "https://restcountries.eu/data/mmr.svg"],
        ['countryname' => "Namibia", 'countrycode' => "https://restcountries.eu/data/nam.svg"],
        ['countryname' => "Nauru", 'countrycode' => "https://restcountries.eu/data/nru.svg"],
        ['countryname' => "Nepal", 'countrycode' => "https://restcountries.eu/data/npl.svg"],
        ['countryname' => "Netherlands", 'countrycode' => "https://restcountries.eu/data/nld.svg"],
        ['countryname' => "New Caledonia", 'countrycode' => "https://restcountries.eu/data/ncl.svg"],
        ['countryname' => "New Zealand", 'countrycode' => "https://restcountries.eu/data/nzl.svg"],
        ['countryname' => "Nicaragua", 'countrycode' => "https://restcountries.eu/data/nic.svg"],
        ['countryname' => "Niger", 'countrycode' => "https://restcountries.eu/data/ner.svg"],
        ['countryname' => "Nigeria", 'countrycode' => "https://restcountries.eu/data/nga.svg"],
        ['countryname' => "North Korea", 'countrycode' => "https://restcountries.eu/data/prk.svg"],
        ['countryname' => "Norway", 'countrycode' => "https://restcountries.eu/data/nor.svg"],
        ['countryname' => "Oman", 'countrycode' => "https://restcountries.eu/data/omn.svg"],
        ['countryname' => "Pakistan", 'countrycode' => "https://restcountries.eu/data/pak.svg"],
        ['countryname' => "Palau", 'countrycode' => "https://restcountries.eu/data/plw.svg"],
        ['countryname' => "Palestine", 'countrycode' => "https://restcountries.eu/data/pse.svg"],
        ['countryname' => "Panama", 'countrycode' => "https://restcountries.eu/data/pan.svg"],
        ['countryname' => "Papua New Guinea", 'countrycode' => "https://restcountries.eu/data/png.svg"],
        ['countryname' => "Paraguay", 'countrycode' => "https://restcountries.eu/data/pry.svg"],
        ['countryname' => "Peru", 'countrycode' => "https://restcountries.eu/data/per.svg"],
        ['countryname' => "Philippines", 'countrycode' => "https://restcountries.eu/data/phl.svg"],
        ['countryname' => "Poland", 'countrycode' => "https://restcountries.eu/data/pol.svg"],
        ['countryname' => "Portugal", 'countrycode' => "https://restcountries.eu/data/prt.svg"],
        ['countryname' => "Qatar", 'countrycode' => "https://restcountries.eu/data/qat.svg"],
        ['countryname' => "Kosovo", 'countrycode' => "https://restcountries.eu/data/kos.svg"],
        ['countryname' => "Réunion", 'countrycode' => "https://restcountries.eu/data/reu.svg"],
        ['countryname' => "Romania", 'countrycode' => "https://restcountries.eu/data/rou.svg"],
        ['countryname' => "Russia", 'countrycode' => "https://restcountries.eu/data/rus.svg"],
        ['countryname' => "Rwanda", 'countrycode' => "https://restcountries.eu/data/rwa.svg"],
        ['countryname' => "Saint Kitts and Nevis", 'countrycode' => "https://restcountries.eu/data/kna.svg"],
        ['countryname' => "Saint Lucia", 'countrycode' => "https://restcountries.eu/data/lca.svg"],
        ['countryname' => "Saint Vincent and the Grenadines", 'countrycode' => "https://restcountries.eu/data/vct.svg"],
        ['countryname' => "Samoa", 'countrycode' => "https://restcountries.eu/data/wsm.svg"],
        ['countryname' => "San Marino", 'countrycode' => "https://restcountries.eu/data/smr.svg"],
        ['countryname' => "Sao Tome and Principe", 'countrycode' => "https://restcountries.eu/data/stp.svg"],
        ['countryname' => "Saudi Arabia", 'countrycode' => "https://restcountries.eu/data/sau.svg"],
        ['countryname' => "Senegal", 'countrycode' => "https://restcountries.eu/data/sen.svg"],
        ['countryname' => "Serbia", 'countrycode' => "https://restcountries.eu/data/srb.svg"],
        ['countryname' => "Seychelles", 'countrycode' => "https://restcountries.eu/data/syc.svg"],
        ['countryname' => "Sierra Leone", 'countrycode' => "https://restcountries.eu/data/sle.svg"],
        ['countryname' => "Singapore", 'countrycode' => "https://restcountries.eu/data/sgp.svg"],
        ['countryname' => "Slovakia", 'countrycode' => "https://restcountries.eu/data/svk.svg"],
        ['countryname' => "Slovenia", 'countrycode' => "https://restcountries.eu/data/svn.svg"],
        ['countryname' => "Solomon Islands", 'countrycode' => "https://restcountries.eu/data/slb.svg"],
        ['countryname' => "Somalia", 'countrycode' => "https://restcountries.eu/data/som.svg"],
        ['countryname' => "South Africa", 'countrycode' => "https://restcountries.eu/data/zaf.svg"],
        ['countryname' => "South Korea", 'countrycode' => "https://restcountries.eu/data/kor.svg"],
        ['countryname' => "South Sudan", 'countrycode' => "https://restcountries.eu/data/ssd.svg"],
        ['countryname' => "Spain", 'countrycode' => "https://restcountries.eu/data/esp.svg"],
        ['countryname' => "Sri Lanka", 'countrycode' => "https://restcountries.eu/data/lka.svg"],
        ['countryname' => "Sudan", 'countrycode' => "https://restcountries.eu/data/sdn.svg"],
        ['countryname' => "Suriname", 'countrycode' => "https://restcountries.eu/data/sur.svg"],
        ['countryname' => "Swaziland", 'countrycode' => "https://restcountries.eu/data/swz.svg"],
        ['countryname' => "Sweden", 'countrycode' => "https://restcountries.eu/data/swe.svg"],
        ['countryname' => "Switzerland", 'countrycode' => "https://restcountries.eu/data/che.svg"],
        ['countryname' => "Syria", 'countrycode' => "https://restcountries.eu/data/syr.svg"],
        ['countryname' => "Taiwan", 'countrycode' => "https://restcountries.eu/data/twn.svg"],
        ['countryname' => "Tajikistan", 'countrycode' => "https://restcountries.eu/data/tjk.svg"],
        ['countryname' => "Tanzania", 'countrycode' => "https://restcountries.eu/data/tza.svg"],
        ['countryname' => "Thailand", 'countrycode' => "https://restcountries.eu/data/tha.svg"],
        ['countryname' => "Timor-Leste", 'countrycode' => "https://restcountries.eu/data/tls.svg"],
        ['countryname' => "Togo", 'countrycode' => "https://restcountries.eu/data/tgo.svg"],
        ['countryname' => "Tonga", 'countrycode' => "https://restcountries.eu/data/ton.svg"],
        ['countryname' => "Trinidad and Tobago", 'countrycode' => "https://restcountries.eu/data/tto.svg"],
        ['countryname' => "Tunisia", 'countrycode' => "https://restcountries.eu/data/tun.svg"],
        ['countryname' => "Turkey", 'countrycode' => "https://restcountries.eu/data/tur.svg"],
        ['countryname' => "Turkmenistan", 'countrycode' => "https://restcountries.eu/data/tkm.svg"],
        ['countryname' => "Turks and Caicos Islands", 'countrycode' => "https://restcountries.eu/data/tca.svg"],
        ['countryname' => "Tuvalu", 'countrycode' => "https://restcountries.eu/data/tuv.svg"],
        ['countryname' => "Uganda", 'countrycode' => "https://restcountries.eu/data/uga.svg"],
        ['countryname' => "Ukraine", 'countrycode' => "https://restcountries.eu/data/ukr.svg"],
        ['countryname' => "United Arab Emirates", 'countrycode' => "https://restcountries.eu/data/are.svg"],
        ['countryname' => "United Kingdom", 'countrycode' => "https://restcountries.eu/data/gbr.svg"],
        ['countryname' => "United States of America", 'countrycode' => "https://restcountries.eu/data/usa.svg"],
        ['countryname' => "Uruguay", 'countrycode' => "https://restcountries.eu/data/ury.svg"],
        ['countryname' => "Uzbekistan", 'countrycode' => "https://restcountries.eu/data/uzb.svg"],
        ['countryname' => "Vanuatu", 'countrycode' => "https://restcountries.eu/data/vut.svg"],
        ['countryname' => "Venezuela", 'countrycode' => "https://restcountries.eu/data/ven.svg"],
        ['countryname' => "Vietnam", 'countrycode' => "https://restcountries.eu/data/vnm.svg"],
        ['countryname' => "Yemen", 'countrycode' => "https://restcountries.eu/data/yem.svg"],
        ['countryname' => "Zambia", 'countrycode' => "https://restcountries.eu/data/zmb.svg"],
        ['countryname' => "Zimbabwe", 'countrycode' => "https://restcountries.eu/data/zwe.svg"],
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->countries as $country) {
            Country::firstOrCreate($country);
        }
    }
}
